const ActionTypes = {
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT: "LOGOUT",

  SIGNUP: "SIGNUP",
  SIGNUP_FAIL: "SIGNUP_FAIL",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",

  GET_USER_ME: "GET_USER_ME",
  GET_USER_ME_FAIL: "GET_USER_ME_FAIL",
  GET_USER_ME_SUCCESS: "GET_USER_ME_SUCCESS",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PROFILE_FAIL: "UPDATE_PROFILE_FAIL",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",

  UPLOAD_PHOTO: "UPLOAD_PHOTO",
  UPLOAD_PHOTO_FAIL: "UPLOAD_PHOTO_FAIL",
  UPLOAD_PHOTO_SUCCESS: "UPLOAD_PHOTO_SUCCESS",

  GET_DATA: "GET_DATA",
  GET_DATA_FAIL: "GET_DATA_FAIL",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",

  GET_INTERMEDIATE_DATA: "GET_INTERMEDIATE_DATA",
  GET_INTERMEDIATE_DATA_FAIL: "GET_INTERMEDIATE_DATA_FAIL",
  GET_INTERMEDIATE_DATA_SUCCESS: "GET_INTERMEDIATE_DATA_SUCCESS",

  GET_FILE: "GET_FILE",
  GET_FILE_FAIL: "GET_FILE_FAIL",
  GET_FILE_SUCCESS: "GET_FILE_SUCCESS",

  UPLOAD_FILE: "UPLOAD_FILE",
  UPLOAD_FILE_FAIL: "UPLOAD_FILE_FAIL",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
};

export default ActionTypes;
